language: ruby

before_install:
  - gem update --system
  - gem install bundler

cache: bundler
script: make build

deploy:
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: build
    committer_from_gh: true
    target_branch: gh-pages
    repo: canvascbl/helpdesk
    edge: true
    on:
      branch: master
